version: '3'

services:
    web:
        container_name: ${CONTAINER_NAME}
        image: nginx
        restart: unless-stopped
        volumes:
            - ${DATA_DIR}:/usr/share/nginx/html
        environment:
            VIRTUAL_HOST: ${DOMAINS}
            LETSENCRYPT_HOST: ${DOMAINS}
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

networks:
    default:
        external:
            name: ${NETWORK}
